### ISSUE TITLE
QtWebKit mishandles some standard keyboard shortcuts (like Ctrl+A)

### ISSUE THREAD

**Issue by Katarn** [Emdek/otter#232]
For example: https://raw.github.com/Emdek/otter/1e040dda8b0eff7b0d1c51de480bca4d44c167ef/src/modules/backends/web/qtwebkit/QtWebKitWebWidget.cpp

**Comment by Emdek** [comment]
I've ran some tests and now I'm convinced that it's something wrong in QtWebKit or WebKit itself.
``QWebPage`` always eats this shortcut, no matter if it can make use of it or not (it works only on form controls like INPUT or TEXTAREA, maybe also other kinds of editable content).
The same applies to some other shortcuts...

It would be best if there would be some more control over shortcuts handled by QtWebKit, at least some switch to disable all of them or with few exceptions (like arrows etc.).

**Comment by Emdek** [comment]
And here is possible solution, but needs careful testing (including flash based text inputs), to avoid regressions:
https://gist.github.com/Emdek/451f2b5a7d66375ff03c

**Comment by bajasoft** [comment]
Another possible solution without a several problems found in previous one (should work for both Ctrl + A and Ctrl + Backspace):
https://gist.github.com/bajasoft/4a0243fc32ccee05c15d

**Comment by Katarn** [comment]
![Good Job!](http://i.imgur.com/rERMhP0.png)
