### ISSUE TITLE
Hide all UI elements on fullscreen

### ISSUE THREAD

**Issue by uahim** [Emdek/otter#364]
right now, there's still both the address bar and the tab bar visible (on Windows)

**Comment by Emdek** [comment]
@ersi-dnd, I'll reconsider option to hide scrollbars later.
I would like to create solution to allow to reshow navigation bar when moving cursor to edge, which should be easier when #31 will be done (I'm considering special fallback toolbar to be used also when there are no tabs).
I don't see need to decide which toolbars should be available in full screen mode but that can be changed in future, if needed.

**Comment by ersi-dnd** [comment]
The popping address bar in full screen is totally not a good idea. I'm sure this is not how you meant it either. 

If someone wants some toolbars visible, it should be possible to assign keybinds to toggle the toolbars. It should also be possible to create a distinct fullscreen mode which would be a set of toolbars/buttons visible specifically in fullscreen mode. This is how Opera did it.

Otherwise no toolbars and no scrollbars, thanks. Just the right-click menu, keybinds, and mouse gestures.

**Comment by ersi-dnd** [comment]
@Emdek *I don't see need to decide which toolbars should be available in full screen mode but that can be changed in future, if needed.*

The thing is this: At first you *did* decide for the users which toolbars should be available. You decided that address bar and tabbar should be available even in full screen mode. 

As it stands now, moving the cursor to upper edge makes the tabbar pop up and the whole webspace jumps. I am quite sure that you don't like a jumping webpage in fullscreen either.

Then, let's assume it is a good idea that some toolbar pops up when the cursor moves to the upper edge in fullscreen mode (I don't think the cursor movement should do anything, but let's forget it for the moment). Should it not be up to the user which toolbar it would be? It could be tabbar, it could be address bar, it could be both, and surely there are users who would like to see a toolbar that they have specifically customised for fullscreen mode. More options!

And speaking of more options, I need an option to set the popup tabbar *off* in fullscreen. I need a clean fullscreen mode where I operate only by keyboard and right-click menus.

**Comment by Emdek** [comment]
@ersi-dnd, sure, but I prefer jump over long and pointless animation and covering top part of page seems to be bad approach...
I'll think about additional options as soon as more important stuff will be ready (I've got motivated already, but need to recover first).

Who wants peace must prepare for a war. ;-)
