### ISSUE TITLE
Override 'Open new tab next to active' in Bookmarks menu & sidebar

### ISSUE THREAD

**Issue by beastie1** [Emdek/otter#475]
Right now, 'Open new tab next to active' is overridden with Alt (since aa1b1da). This works well when middle-clicking (Alt+MMB) a link.

But 'Alt' closes menus, so it doesn't work in the Bookmarks menu.

And it also doesn't work within the Bookmarks sidebar.

**Comment by Emdek** [comment]
Is there something missing in current master to close this ticket?

**Comment by beastie1** [comment]
The Bookmarks sidebar part works fine now, but not the Bookmarks menu part because 'Alt' still causes menus to close (at least if does on my system).

When **TabBar/OpenNextToActive** is set to true and you middle-click a link while 'Alt' is pressed, the link opens as the last tab.

Right now the only way to open a bookmark (from the Bookmarks menu) as the last tab is to set **TabBar/OpenNextToActive** to false.

**Comment by Emdek** [comment]
@beastie1, that behavior for Alt is apparently a "feature" of all Qt applications, so we can't do much about that unless upstream would decide to change this (as it can be considered as a bug).
