### ISSUE TITLE
DEB package doesn't add Otter to the Alternatives System

### ISSUE THREAD

**Issue by Frenzie** [Emdek/otter#496]
`update-alternatives --config x-www-browser` doesn't show Otter after installing the Debian package.

I could look into this myself since it should be easy to fix, but I'm not an expert at this stuff or anything so someone else feel free to pick it up. I believe this has to be implemented in [maintainer scripts](http://www.debian.org/doc/debian-policy/ch-maintainerscripts), specifically postinst and prerm. Example scripts should be able to be found in any other browser, for instance:

https://packages.debian.org/jessie/chromium
https://packages.debian.org/jessie/netsurf-gtk
https://packages.debian.org/jessie/qupzilla

I imagine they all use `update-alternatives --install` and `update-alternatives --remove` within an if statement, but that's the part that'd take a modest amount of time to investigate. `man debhelper` does not suggest the existence of any kind of dh_alternatives script that would be of help.

**Comment by Emdek** [comment]
I guess that we can close it now, since now we have official PPA for Ubuntu, updated Debian packaging instructions but no official packages for Debian anyway.
