### ISSUE TITLE
Crash after editing userAgents.ini

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#548]
1. Close Otter
2. open userAgents.ini 
3. Find this
    [firefox]
    title=Mask as Mozilla Firefox 21 (Windows) 
    value="Mozilla/5.0 (Windows NT 6.1; rv:21.0) Gecko/20130328 Firefox/21.0"
4. Replace it with this (not sure if it's legit value, but this should not matter for the crash)
    [firefox]
    title=Mask as Mozilla Firefox 33 (Windows)
    value="Mozilla/5.0 (Windows NT 6.1; rv:33.0) Gecko/20100101 Firefox/33.0"
5. Save the file and close.
6. Open Otter, and select identify as Firefox 33.
7. Crash.

I think userAgents.ini should tolerate manual editing. It should tolerate any value.

**Comment by Emdek** [comment]
No backtrace + moving it JSON anyway = bug closed. ;-)
