### ISSUE TITLE
Placement of pinned tabs when new session is opened within current window

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#593]
Looks like pinned tabs are meant to be leftmost on the tabbar. However, when I have a session with pinned tabs saved, and then I open it in a current window, then the pinned tabs are opened to the right from the current window. Still displayed as pinned, but not leftmost. 

Maybe the fix could be to open a new session in the current window *entirely to the left of the currently open set of tabs*.

**Comment by Emdek** [comment]
OK, now I've checked how exactly does it behave and it seems to be fine.
If we really need to fully reverse it then it can be done as part of #190.
