### ISSUE TITLE
ContextMenu action

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#606]
When doing spatial navigation in Opera, there was a "Show context menu" action that did the equivalent of right-click in that place. Is there such an action planned in Otter? When will it be available?

**Comment by ersi-dnd** [comment]
I meant this ticket as that there should be an action (accessible by e.g. keyboard shortcut) that would do the same as right-click pertaining to that place where the focus happens to be. Opera has this.

**Comment by Emdek** [comment]
@ersi-dnd, uhm, it's not enough?
http://en.wikipedia.org/wiki/Menu_key
It should work better with recent code.

**Comment by ersi-dnd** [comment]
Doesn't work at all on my end on the one computer where I have that button. With the latest git version that I installed ten minutes ago.

**Comment by Frenzie** [comment]
Confirmed. The menu key doesn't work for me either in Otter. In Opera there's a configurable action for it, Shift + F10 by default. I bound it to F9 in my customized setup, although that's a bit of a waste of a perfectly good function key on my proper desktop keyboard.
![screenshot-20150104-opera-showcontextmenu-fs8](https://cloud.githubusercontent.com/assets/202757/5606299/1c301dac-9429-11e4-8dc2-9d053cae560b.png)

**Comment by Emdek** [comment]
Lets continue talk about spatial navigation related issues in #119.
It might be possible to try to emulate Enter on SELECT etc. by faking left mouse button clicks, but that won't work in all cases.
