### ISSUE TITLE
Bookmark duplicates policy

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#618]
When a bookmark is saved and user navigates on the same page and clicks on the address field star or chooses "Add bookmark" from the menu, a dialogue informs the user that such bookmark already exists. When the user chooses to continue from there, a new bookmark dialogue opens up. 

I have a suggestion to enhance this behaviour with an option in about:config AllowDuplicateBookmarks true/false. Both options would give the same warning as described, but when the duplicates policy is set to "false", the new bookmark dialogue would contain the existing bookmark data. 

I mean, when AllowDuplicateBookmarks is false, then selecting "Add bookmark" on a page already bookmarked, the user would see the existing bookmark edit dialogue, not adding a new dialogue. 

And the "This bookmark already exists. Continue?" dialogue should have three options: 1. Yes 2. Cancel 3. Never show this message again

And about:config should contain an option to get the dialogue back.

**Comment by Emdek** [comment]
Treating them differently is intentional, it will make more sens after finishing #510 (global action will have fixed text).
