### ISSUE TITLE
CTRL+TAB in combination with Transfers Manager

### ISSUE THREAD

**Issue by scriveyn** [Emdek/otter#627]
Installation: weekly #52 / Win7
Issue: CTRL+TAB in combination with Transfers Manager does not work / gives unpredictable results

Can you confirm this?

**Comment by reesmichael1** [comment]
Disabling "tabKeyNavigation" in the transfersView QTableView properties seems to fix this. 

With "tabKeyNavigation" enabled, I have to press the tab key eight times to cycle from the first item in the Transfer Manager to the second, and then eight times to go from the second to the third, and so on. This doesn't seem like the intended behavior, so it you want to leave "tabKeyNavigation" enabled, this would be worth looking into.

With "tabKeyNavigation" disabled, this particular bug is fixed, but pressing the tab key instead cycles the focus through the various elements of the Transfer Manager, at least when the initial focus is on a downloaded item. This may be easy to fix, but if it is, I don't immediately know how.

Would it be worth it to disable "tabKeyNavigation"? Can the selecting different parts of the UI be fixed? I'd be happy to investigate this more and open a pull request, but I wanted to let you know about what I've found while looking at this issue and get your thoughts on how it should be approached.

**Comment by scriveyn** [comment]
@reesmichael1: Not sure whether this is intended for me. Should I take it that "tabKeyNavigation" in the transfersView QTableView properties" is something that will be set during build?

"pressing the tab key [..] cycles the focus through the various elements of the Transfer Manager" That is what Opera (my 11.52 insallation) does; not the download items, but the UI elements.
For cycling through/selecting the download items I use arrow up/down.

**Comment by Emdek** [comment]
@reesmichael1, thanks for spotting that, defaults might be annoying sometimes. ;-)
If it would make sense we could reimplement handling of Tab there so it would be ignored when there are modifiers set but I don't think that it would be worth the effort.
