### ISSUE TITLE
Tab bar position resets after each restart in beta 4 on Win32

### ISSUE THREAD

**Issue by uahim** [Emdek/otter#636]
i.e. it's always back on top, wherever you have dragged it before, and the side bar/panel is not visible at all, despite
```
[Window]
SidebarWidth=300
```
in the conf. is this a bug?

I noticed that before - up until the latest weekly - there was more settings stored in otter.conf:
```
[Window]
Geometry=@ByteArray(...)
State=@ByteArray(...)
SidebarWidth=300
```

**Comment by uahim** [comment]
ah Emdek was faster than me, it's already addressed in https://github.com/Emdek/otter/issues/31

**Comment by Emdek** [comment]
They were moved to session (to let different sizes and positions for windows in session) and position of toolbars (and sidebars etc.) will be moved to *toolBars.json* as part of #31.

**Comment by uahim** [comment]
I see, so the workaround - for me - until then looks like this: saving an empty tab as a session, and re-opening it each time Otter has to be restarted.
