### ISSUE TITLE
Go to This Address is not doing anything

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#637]
1. Open a webpage and select some text
2. Right-click
3. Select Go to This Address in the menu

It opens a new empty tab for me. Surely it should do more.

**Comment by ersi-dnd** [comment]
Now it launches a search/go on the address bar, BUT:

In Opera, there is a consistent idea behind such launching actions. When ReuseCurrentTab is true, then it launches in the same tab, but - with the same setting - when you Shift+select, then it launches in new tab. 

I tried select, Shift+select and Ctrl+select. All open up in the same tab. This is still a bug.

**Comment by Emdek** [comment]
@ersi-dnd, it's a missing feature, not a bug (and in case of removed feature it would be a regression). ;-)
I'll check what can be done about that but lets use proper naming.
BTW, I'm reminding you about IRC.
