### ISSUE TITLE
Display the number of matches in Find bar

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#641]
It would be a nice touch to have the Find bar display the number of matches, so the user would know what's wrong when the Find doesn't show the expected text. It might be because the text is not there. 

And I'd still like the font and background colours in the Find field to be editable. What I specifically need is that there would be no change of colour when I begin typing. There may be a change colour with no matches  found (the red or pink background) but I surely don't need any change of colour before this event.

**Comment by Emdek** [comment]
Not doable, at least not without own implementation using JS, so unacceptable in case of WebKit (as it won't work when JS is disabled).
We need some research before taking any action for customizing colors, so we will stay compatible with old skins: #36.

**Comment by ersi-dnd** [comment]
I don't see how it requires JS. I see that the thing is already there and it requires only a wise final touch. 

It's there this way: When I type something in the Find field, then there appear highlighted matches on the page. Surely this information of the existing matches exists somewhere and can be displayed in more ways than the highlights on the page. The highlighted matches surely know their own number without JS, don't they?

By the way, I tried this thing right now in DWB. I turned off all JS (in several settings) and then performed Find. It shows the number of matches. Then I restarted DWB and tried again. It again showed the number of matches. From what I see, it should be possible to do.

**Comment by Emdek** [comment]
@ersi-dnd:
``bool QWebPage::findText(const QString & subString, FindFlags options = 0)``
It's only **bool** and we can't do nothing about that, we could change that only by forking QtWebKit but that won't happen (if we had to fork such monster then we would go for QtWebEngine instead, WebKit is dead and QtWebKit itself is marked as deprecated).
We can revisit that for other backends, for now it is impossible.

**Comment by ersi-dnd** [comment]
Bool is like binary (yes/no, on/off, 0/1), right? This much I can understand.

**Comment by Emdek** [comment]
@ersi-dnd, yes, we would need ``int`` instead.
QtWebKit has the lowest quality of all Qt modules (and is the biggest one, almost as big as all other modules together, except QtWebEngine which is even bigger) and has very chaotic APIs, it wasn't designed to serve real browsers so new APIs were added as needed, in backwards compatible way so now we have what we have...
Hopefully QtWebEngine will be at least a bit better and if it won't then we will fork it (with help of other projects if needed).
