### ISSUE TITLE
Navigation buttons are disabled

### ISSUE THREAD

**Issue by ghost** [Emdek/otter#642]
the menu button puts you back in history only when using its dropdown menu

**Comment by Emdek** [comment]
Works for me (both Linux and Windows), any additional details?
Note that long press (and how long it takes to be considered as such is probably platform dependent) will always bring menu.

**Comment by resbro** [comment]
Wasn't this issue #390 at one point? I don't think it's an Otter thing, Many site won't let you back without double clicking back button or using the dropdown history back arrow. Does it in Opera too. and Chrome , and Palemoon not to mention IE. I don't even think about it any more, I just automatically double click back when they won't let me single backclick....(or use the dropdown list...)

**Comment by justintimberland** [comment]
Like #390 but not a problem with amazon

**Comment by Emdek** [comment]
@justintimberland, and what happens when using rocker navigation, shortcuts or actions from context menu / menu bar / menu button?
I would like to know if it is an issue with button or action itself.

**Comment by justintimberland** [comment]
-double clicking as described in #390 does not work.
-no custom json
-history forth button not greyed out when back button not working

**Comment by Emdek** [comment]
@justintimberland, uhm, this is interesting, when these actions are disabled (and are when QtWebKit says that there is no history to go forward of back) then toolbar buttons should be disabled completely.
These actions are updated in ``QtWebKitWebWidget::updateNavigationActions()``:
https://github.com/Emdek/otter/blob/master/src/modules/backends/web/qtwebkit/QtWebKitWebWidget.cpp#L496
I could prepare small debug patch to be applied here, printing information about state of these actions.

**Comment by resbro** [comment]
The behavior I have seen can be reproduced on ESPN (usa). Say you go to mainpage and select NBA from the bar across the top and then on the right menu select say "Daughter of Lakers GM dies", When you get to that page, you cannot just back up with one click of the back button to the prevous NBA page. Double back clicking will take you back. Same for the next page back. 

Win 7x64
Otter Beta 4x2 x64bit

**Comment by justintimberland** [comment]
reload button also without function, context reload ok

**Comment by Emdek** [comment]
@justintimberland, it seems that on your system buttons stay disabled for some reason.
Could you please post screenshot or screencast showing both main window and context menu of page?

**Comment by justintimberland** [comment]
I "deleted" my profile, uninstalled otter, reinstalled it.
Only difference I realized: New Tab button without function...
I switched back to my old profile, New Tab button without function

**Comment by resbro** [comment]
Wow, I'm not having any of that now, except for the not remembering the size of the window  and state of sidebar thing, weekly 53 runs right (even on Amazon). Both x32 and x64.

**Comment by justintimberland** [comment]
Doing an ldd turned out that otter is using the qt5.3 files from the debian installation, even though it was compiled using the optional qt5.4 files.
Doing an ldd with qupzilla shows me that qupzilla is using the qt5.4 files it is compiled with.

**Comment by Frenzie** [comment]
Unless I misunderstand the steps to reproduce, the back/forward actions work in every way I can conceive.[1] Tested in Debian Jessie x64 both compiled against its included Qt 5.3.2 and against Qt 5.4.

[1] Single-click the back/forward buttons, long-click for dropdown, history menu, `z` & `x`, and flipback/flipforward.

**Comment by justintimberland** [comment]
I do not understand why otter doesn't use the files from the qt5.4 installation it was compiled with/against.

For testing I installed the version from http://ppa.launchpad.net/otter-browser/daily/ubuntu/, same problem with the buttons plus the bugs from qt5.3.2

**Comment by Emdek** [comment]
@justintimberland, so you are seeing this issue under Ubuntu 14.10 using system wide Qt?

**Comment by justintimberland** [comment]
Debian testing, defaults to qt from debian testing, but ubuntu repositories available, do not know which ones are used for satisfying the dependencies

**Comment by justintimberland** [comment]
After using qtcreator to compile otter, (ldd says) it is using the correct qt5.4 files from the opt install.
When compiling with cmake, otter is running with the wrong qt files from debian.

**Comment by Frenzie** [comment]
Ah yes, I used QtCreator. Maybe there's some flag you need to set at compile time?

**Comment by Emdek** [comment]
So it seems to be kind of packaging issue, it is possible that such issue might happen if at runtime application is using version older than the one which was used at compile time (it might even simply crash in such cases).

**Comment by justintimberland** [comment]
Enabling the option "reuse current tab" disables the new tab button!
Disabling this option makes every bookmark open in a new tab, that's annoying.
When "reuse current tab" is disabled, history buttons and the reload button seem to work fine, back button flashes up, indicating there is a history, but... when enabling "reuse current tab" again and clicking on the new tab button, the back button immediately greys out and does no longer work!

**Comment by Emdek** [comment]
@justintimberland, it's unrelated to settings, issue with New Tab button is already fixed.
It looks like issue with incorrect Qt version being picked up at runtime, see:
http://www.cmake.org/Wiki/CMake_RPATH_handling

**Comment by Emdek** [comment]
I guess that we won't get any updates on this issue...
I'm planning to add runtime warning if loaded Qt version is older than that which was used at compile time, RPATH handling is up to package maintainers.
