### ISSUE TITLE
Bookmarks dropdown menu sometimes does not close by itself

### ISSUE THREAD

**Issue by justintimberland** [Emdek/otter#643]

**Comment by Emdek** [comment]
Any additional information?
If there is no reproducible way to reproduce it then we won't be able to fix it.
It's handled here:
https://github.com/Emdek/otter/blob/master/src/ui/Menu.cpp#L561

**Comment by justintimberland** [comment]
It stays open on previously empty tabs only. Both 64bit and 32bit tested on windows.

**Comment by Emdek** [comment]
@justintimberland, cannot reproduce so far.
I've tried with both bookmark in submenu and in Bookmarks menu itself, using left and middle mouse button, with and without keyboard modifiers and using bot menu bar and menu button
.
Are there any interesting differences in your setup comparing to standard profile (custom menu bar or custom menu button etc.)?
Windows 7 32 bit.

**Comment by resbro** [comment]
It happens to me again but differently this time. When I open a bookmark (from the toolbar) the menus all open. however, if its a bookmark in a folder in a folder, the first bookmark dropdown menu returns to menubar, however, the second and third (etc.) deep menus remain focused until you click on the page itself (it does actually open the correct page under the remaining menus/submenus)

Win 7
Otter Beta 4

**Comment by Emdek** [comment]
@resbro, indeed, I could reproduce it with one more level.

**Comment by justintimberland** [comment]
Same on debian

**Comment by Emdek** [comment]
@justintimberland, version from before or after that commit?

**Comment by justintimberland** [comment]
latest git version from today, 0.9.05-dev, qt 5.4.0

**Comment by justintimberland** [comment]
Now the menu closes by itself after staying open for a second or so, this creates the impression that otter is more ponderous than other browsers.

**Comment by Emdek** [comment]
@justintimberland, I've noticed that but there is not much that I can do about that right now.
