### ISSUE TITLE
Beta 4 not working on Windows 8

### ISSUE THREAD

**Issue by MazheM** [Emdek/otter#644]
When i try to start Otter Beta 4(i trying otter-browser-win64-beta4-v2.zip, otter-browser-win64-beta4.zip and otter-browser-win32-beta4.7z) i get ![this error](https://cloud.githubusercontent.com/assets/5282790/5604357/371e1f8e-93c9-11e4-97c2-3f9042ab599b.png).
On Windows 7 all start ok.

**Comment by Frenzie** [comment]
It seems to work for me in 32-bit Windows 8, so I guess it's 64-bit Windows 8 specific.

**Comment by MazheM** [comment]
Yeah, i have 64-bit Win 8. Seems on Win 7 64-bit its work too

**Comment by bajasoft** [comment]
I just tested it on clean Windows 8.1 x64 - both versions works fine.
@MazheM, do you have in your folder where Otter is installed "platforms" subfolder with "qwindows.dll"? There should be also "qminimal.dll" and "qoffscreen.dll".

**Comment by MazheM** [comment]
Yeah, i check it when get error, all dlls present in the folder

**Comment by Frenzie** [comment]
@MazheM Did you try if it works with the installer?

**Comment by MazheM** [comment]
@Frenzie Test with installer and it works fine.

**Comment by Emdek** [comment]
@MazheM, thanks for testing, I've added note to README which will be used starting with next weekly that installers are recommended.
