### ISSUE TITLE
crash on opening the first tab

### ISSUE THREAD

**Issue by vbr** [Emdek/otter#649]
Hi,
first of all, many thanks for your continued efforts in developing Otter!
I'd like to report a crash of the browser, which happens consistently (for me), after closing all tabs and creating a new empty tab (be it via menu item, tabbar icon or Ctrl+T shortcut).
(The only way to get a usable tab after previously closing all of them seems to be to open some item from the bookmarks and reuse its tab.) 
I am using Otter 0.9.05 weekly 53, Win7.
Regards,
   vbr

**Comment by Emdek** [comment]
Fixed in 725c99abf93c88e5cb5f46fbe5575d0817a1998d.
