### ISSUE TITLE
Tabs rendering problems - Graphical Glitch or DPI Windows related problem?

### ISSUE THREAD

**Issue by SJ-Diamond** [Emdek/otter#650]
![tabs](https://cloud.githubusercontent.com/assets/1733238/5663585/2e642838-9749-11e4-8ce3-b4b46f127beb.png)

As the pic shows, for me using Otter Weekly 53 the tabs are, when mouse hovered over, only partly marked/filled/animated/rendered as the picture shows.

Also in background state this effect is visible like explained above.Only when one tab is active, it is rendered error free. The following pic shows that quite visible.

![tabs2](https://cloud.githubusercontent.com/assets/1733238/5663680/40eb000c-974a-11e4-8a75-6f2697791173.png)

Graphical glitch? Or could that be in relation that i have a custom DPI setting in Windows of 150%?

System where the problem appears is Windows 7 64 Bit, using Otter Weekly 53.

**Comment by Frenzie** [comment]
I believe that Qt 5.4 is supposed to support DPI scaling fully, but maybe there are still a few glitches left?

Possibly relevant link drop:
http://blog.davidedmundson.co.uk/blog/kde_apps_high_dpi
http://thedndsanctuary.eu/index.php?topic=579.0

**Comment by SJ-Diamond** [comment]
No glitch like this under Windows 8 64 Bit. There the tabs are shown glitch
free.

2015-01-08 16:22 GMT+01:00 Frans de Jonge <notifications@github.com>:

> I believe that Qt 5.4 is supposed to support DPI scaling fully, but maybe
> there are still a few glitches left?
>
> Possibly relevant link drop:
> http://blog.davidedmundson.co.uk/blog/kde_apps_high_dpi
> http://thedndsanctuary.eu/index.php?topic=579.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emdek/otter/issues/650#issuecomment-69193810>.
>



-- 
---------- Wikus Van De Merwe was right - Fookin' Planet!!! ----------

**Comment by Emdek** [comment]
This is clearly upstream issue (we don't use custom drawing yet), but good to know about that, we will have to take it into account in #190.
