### ISSUE TITLE
Per site user css no longer working

### ISSUE THREAD

**Issue by justintimberland** [Emdek/otter#651]
only global user css accepted and applied

**Comment by Emdek** [comment]
Works fine here, using extreme example (red text and background for per site CSS and green text and background for global CSS):
http://im9.eu/picture/red
http://im9.eu/picture/green
Note that Override has to be unchecked to get global CSS, keeping it checked may result with no global CSS.

Related ticket: #533.

**Comment by justintimberland** [comment]
Does not work here on win7. I have 2 css files in my profile, one is used global for all sites to highlight visited links, the other one is used only on one site to zoom it in. When selecting the latter in the website's preferences ui, it gets not applied, the setting is always jumping back to the global css.

**Comment by justintimberland** [comment]
None of the per-site override settings being saved
