### ISSUE TITLE
Cycle tabs with scrollwheel

### ISSUE THREAD

**Issue by landroni** [Emdek/otter#657]
Please allow to cycle tabs using the scrollwheel. This wasn't part of Opera 12.x, but in my opinion it was a glaring omission. Most tabbed Gtk or Qt apps allow cycling tabs using the scrollwheel (e.g. LyX, Midori, Xfce4 Terminal, etc.).

This is very useful for those used to such behavior (not unlike mouse gestures), and I'd love to see this in Otter.

**Comment by Emdek** [comment]
We allow to do that, but you need to set this option to do that without Ctrl: **TabBar/RequireModifierToSwitchTabOnScroll**.

**Comment by landroni** [comment]
Should this have a GUI counterpart?

**Comment by landroni** [comment]
Also, all apps with this behavior do not wrap at the end of the tab list. Does Otter allow cycling to stop when reaching the first/last tab?

**Comment by Emdek** [comment]
@landroni, what kind of GUI counterpart?
UI to set options or showing list of tabs when cycling?

In our case after reaching last tab the next one will be first one and after reaching first the next one will be the last one.

**Comment by landroni** [comment]
@Emdek 

*what kind of GUI counterpart?*

UI to set options. I still think scrollwheel without ctrl should be the default (as elsewhere). But if not, then a UI to set this option should be available in Settings. 

*after reaching last tab the next one will be first one and after reaching first the next one will be the last one.* 

Yes, absolutely. What I mean is that this behavior is not very useful for all users, and it's downright aggravating for those expecting scrolling to stop when reaching the last tab, or the first tab. It would be nice to have, say, a hidden option enabling/disabling "wrapping around tabs".

**Comment by Emdek** [comment]
@landroni, it seems to be enabled by default only in Chromium (counting only mainstream browsers), which also doesn't wrap.
We can add these options to context menu of tab bar, but we would need some nice user visible names for these two options (something shorter than: "Enable Tab Cycling on Mouse Wheel Scroll" ;-)).

**Comment by landroni** [comment]
@Emdek Chromium and Midori are already big hitters, IMO. :) I guess for novice users it's much more useful to have this enabled by default, which they can find out easily, and an easy way to disable behavior. 

Mayhaps: "Tab Cycling on Wheelscroll" checkbox? 

:)

**Comment by Emdek** [comment]
@landroni, none of WebKit-based browsers are mainstream (as Blink-based already deserve own category). :-P
Maybe except Safari which is special case.

I think that I prefer Cycle over Switch, but deciding how to phrase it correctly seems more like a task for some linguist. ;-)

**Comment by landroni** [comment]
:) I guess ultimately it's the functionality that matters. As long as the option can be understood by a user, whether long or short...

**Comment by Frenzie** [comment]
@Emdek 

> I think that I prefer Cycle over Switch, but deciding how to phrase it correctly and in compact way seems be a task for some linguist. ;-)

They're both fine. I'd propose something like "Switch pages using the mouse wheel" or "Cycle through pages using the mouse wheel". However, that's without yet taking into consideration that this could be confused for the imo more important right click + scroll functionality.

**Comment by Emdek** [comment]
@Frenzie, I like that variant, but I would consider changing "pages" to "tabs".
It could confuse only those who are aware of that feature in Opera. ;-)

**Comment by landroni** [comment]
Yeah, I too think "tabs" is better than "pages". Most people will think in terms of tabs for this functionality...

**Comment by landroni** [comment]
Thanks for providing the option! Looks great!

Here's a relevant discussion on the same subject (even if in a different context): 
https://bugzilla.xfce.org/show_bug.cgi?id=6401#c6

The bottom line is that most apps---in instances of switching workspaces/windows/tabs with mouse scrollwheel---use *no wrapping* by default. For instance, there is no wrapping when switching tabs via scrollwheel in Midori, LyX, Chromium or Geany. And there are good theoretical arguments for this too (see link above). 

So I think `no wrapping` should be the default in Otter, too, with a hidden option allowing power users to revert behavior if they wish so.

**Comment by Emdek** [comment]
Related work #190 (required for proper wrapping control).
