### ISSUE TITLE
[Linux] Some errors KLauncher and Youtube

### ISSUE THREAD

**Issue by elav** [Emdek/otter#660]
Great job. I love Otter. 

I use Arch Linux with KDE 64bit 4.13. In the short time I've tried Otter I found some errors, for example, I do not detect past tildes a while, and was not able to load the data in the file window when trying to upload or save an image from hard disk, because I returned the error:

    Could not start the process can not talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files. 

I can not watch videos on Youtube using Flashplayer. Thanks

**Comment by Emdek** [comment]
I've found similar issue here:
https://bbs.archlinux.org/viewtopic.php?id=190617

Flash player is beyond our control, I can only suggest to upgrade Qt5 to 5.4.0 (if you are using older version) which may help.
It should work fine with player provided by Adobe, I have no idea if alternative players are supported by QtWebKit.
