### ISSUE TITLE
Make Tabs Have Rounded Corners

### ISSUE THREAD

**Issue by opticyclic** [Emdek/otter#666]
The tabs on Opera 12.17 have rounded corners but the tabs in Otter have very sharp corners.

**Comment by Emdek** [comment]
It's up to theme, currently we are using native style, but we plan to add support for Opera themes, so it makes it duplicate of #36.

**Comment by opticyclic** [comment]
If you are using native style, why are the default bookmark icons KDE blue and not Windows yellow?

**Comment by Emdek** [comment]
@opticyclic, icons are not part of theme, although in this specific case we could try to use `QStyle::SP_DirIcon` (one of standard pixmaps).

See also:
http://doc-snapshot.qt-project.org/qt5-5.4/qicon.html#fromTheme
