### ISSUE TITLE
Print Preview Crashes On GitHub

### ISSUE THREAD

**Issue by opticyclic** [Emdek/otter#668]
Print Preview causes Otter to crash on GitHub pages e.g. https://github.com/Emdek/otter but works fine for some other pages e.g. http://www.google.com

**Comment by The-Compiler** [comment]
I also noticed this in https://github.com/The-Compiler/qutebrowser/issues/326 - it seems to be the same issue as reported here: https://bugreports.qt.io/browse/QTBUG-43322

You're also on Windows I guess?

**Comment by resbro** [comment]
Issue 497?

Yeah windows

**Comment by Emdek** [comment]
@resbro, yeah, looks like duplicate of #497.
