### ISSUE TITLE
segfault on site crunchbang.org

### ISSUE THREAD

**Issue by GitHub-devel** [Emdek/otter#671]
When try to enter this site - application get crash with segfault.

**Comment by The-Compiler** [comment]
What Qt version are you on? Works fine here on 5.4. This sounds like an upstream Qt issue which has been resolved already, but your distribution is still on an older version.

**Comment by GitHub-devel** [comment]
You was right, after upgrading Qt from version 5.3.2 to 5.4 the crash is gone. Closing.
