### ISSUE TITLE
vk.com fullscreen image view does not work

### ISSUE THREAD

**Issue by kinik** [Emdek/otter#672]
How to reproduce:

1) Go to vk.com (need registration);
2) Click on any picture
3) Try to make it fullscreen (screenshot: http://itmag.es/6GxL3) you will see black screen for a second, then page pith picture again

My setup:
otter version - beta 4
Slackware-current
qt version 4.8.6, qt-5 also installed 
I saw, that there is error console, but i do not know, how to launch it.

P.S. Thanks for your great job!

**Comment by Emdek** [comment]
Is it JS fullscreen API or just some kind of Lightbox like script (in this case we can propagate this report upstream)?
QtWebkit doesn't support fullscreen API, it is planned for QtWebEngine.
Note that we use only Qt5, see Help / About Qt to check which version are you using.

**Comment by MazheM** [comment]
Fullscreen API.
![vk fullscreen](https://cloud.githubusercontent.com/assets/5282790/5915568/36dc7bfe-a618-11e4-8152-6719cd4067f9.png)

**Comment by Emdek** [comment]
@MazheM, then it has to wait for full implementation in QtWebEngine, I can only guess that it might be added in Qt 5.5 or 5.6. :-/
