### ISSUE TITLE
Opera is dead; enter Vivaldi

### ISSUE THREAD

**Issue by uahim** [Emdek/otter#673]
https://vivaldi.com/
a tech preview is out now

http://www.cnet.com/news/ex-opera-ceo-launches-new-browser-vivaldi/
etc
according to German magazine heise.de it is based on Blink and V8

(this is, of course, not an Otter issue, but it's competition of sorts so I thought I'd write about it here)

**Comment by Emdek** [comment]
See #615, Blink + V8.

**Comment by uahim** [comment]
sorry, I should have checked the forums first

**Comment by Piter432** [comment]
Hmm... why you don't try to make the best customizable browser also with
Jon and his contributors? Both goal of Otter and Vivaldi browsers are the
same, I think.

**Comment by Emdek** [comment]
@Piter432, yes, they are very similar, but not the same.
First of all closed source (apparently) vs open source, second one: multiple backends.
And these are just few of them.

It would mean ditching 18 months of work, from 32 contributors and even more translators and other supporters.
That would be kind of betrayal. ;-)

Their UI is based on Chromium, probably very closely to Opera 15+ (but with a bit weird colors), totally incompatible with our internal concepts.

Note that they were aware of this project for a year (someone posted topic on their website) and nobody ever tried to contact me. And I'm assuming that they started work even before Opera 15 had surfaced.

**Comment by beastie1** [comment]
Nah, it's not competition. At least for me, it's not an alternative. The only closed source program I had been using for years was Opera and after what they did (1. the technical changes made to the software and 2. their disregard for the community) and the way they did it, I can't trust closed source for everyday use programs anymore.

At least with an open source project you can fork. With closed source, it's technically and legally difficult/impossible.

**Comment by Piter432** [comment]
But you will promote Vivaldis browser or not? If not, why?

**Comment by SJ-Diamond** [comment]
In such an early state it is hard to say anything about this one. One thing
for sure, it offers out of the box more interesting customization options
as compared with the "real Opera" - and seen from a power user's
perspective, Vivaldi Browser is much more attractiv as the simple user
Opera browser concept.

Still, Open Source is the way to win :D

2015-01-27 20:00 GMT+01:00 Piotr Karol Żółtowski <notifications@github.com>:

> But you will promote Vivaldis browser or not? If not, why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emdek/otter/issues/673#issuecomment-71706137>.
>



-- 
---------- Wikus Van De Merwe was right - Fookin' Planet!!! ----------

**Comment by Emdek** [comment]
@Piter432, why should I do such thing?
I don't see them doing the same for us.

**Comment by Felipefpl** [comment]
Emdek - keep going with otter, i have doubts if vivaldi will be like the old Opera, btw, it's funny how Jon EX-CEO of Opera acknowledges that the devs of Opera dont give a damn about its users now. :)

**Comment by Emdek** [comment]
@Felipefpl, I've seen it one year ago, I thought that it would be dry by now. :-D

@Piter432, I've got some interesting email, details shall follow as soon I'll get a reply.

**Comment by mgraham** [comment]
They've started implementing spatial navigation. I wonder if any of their work made its way upstream?

**Comment by Piter432** [comment]
@Emdek Well, how is with that email you've got? Did you get the reply from someone to your email?

**Comment by Emdek** [comment]
@Piter432, yeah, but it changed nothing. ;-)
